# Generated by Django 4.1.5 on 2023-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="accountNo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="money",
            field=models.IntegerField(default=0),
        ),
    ]
